name: 'tdb_transformation'
version: '1.0.0'
profile: 'tdb_transformation'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  tdb_transformation:
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: table
      substack:
        +schema: stg_substack

    intermediate:
      +materialized: table
      substack:
        +schema: int_substack

    mart:
      +materialized: table
      substack:
        +schema: mart_substack